---
name: Checkov Scanning
on:
  push:
    branches:
      - master
      - main
jobs:
  checkov-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: Terraform-AZURE-Services-Creation
          framework: terraform